


/* 

Example: Objects as function parameters

*/

var person = { 
    firstname:"Tom", 
    lastname:"Hanks" 
 }; 
 var invokeperson = function(obj: { firstname:string, lastname :string }) { 
    console.log("first name :"+obj.firstname) 
    console.log("last name :"+obj.lastname) 
 } 
 invokeperson(person)


 /* 
 
 The example declares an object literal. The function expression is invoked passing person object.

On compiling, it will generate following JavaScript code.

//Generated by typescript 1.8.10
var person = {
   firstname: "Tom",
   lastname: "Hanks"
};

var invokeperson = function (obj) {
   console.log("first name :" + obj.firstname);
   console.log("last name :" + obj.lastname);
};

invokeperson(person);
Its output is as follows −

first name :Tom 
last name :Hanks
You can create and pass an anonymous object on the fly.
 
 */