

/* 

Example: Anonymous Object

*/

var invokeperson = function(obj:{ firstname:string, lastname :string}) { 
    console.log("first name :"+obj.firstname) 
    console.log("last name :"+obj.lastname) 
 } 
 invokeperson({firstname:"Sachin",lastname:"Tendulkar"});

 /* 
 
 On compiling, it will generate following JavaScript code.

//Generated by typescript 1.8.10
var invokeperson = function (obj) {
   console.log("first name :" + obj.firstname);
   console.log("last name :" + obj.lastname);
};

invokeperson({ firstname: "Sachin", lastname: "Tendulkar" });
invokeperson({ firstname: "Sachin", lastname: "Tendulkar" });
Its output is as follows −

first name :Sachin 
last name :Tendulkar
 
 */