


/* 

The instanceof operator
The instanceof operator returns true if the object belongs to the specified type.

Example

*/

class Person{ } 
var obj = new Person() 
var isPerson = obj instanceof Person; 
console.log(" obj is an instance of Person " + isPerson);

/* 

On compiling, it will generate following JavaScript code.

//Generated by typescript 1.8.10
var Person = (function () {
   function Person() {
   }
   return Person;
}());

var obj = new Person();
var isPerson = obj instanceof Person;
console.log(" obj is an instance of Person " + isPerson);
The output of the above code is as follows −

obj is an instance of Person True 

*/