


/*

Optional parentheses for a single parameter

*/

var display = x=> { 
    console.log("The function got "+x) 
 } 
 display(12)

/* 

On compiling, it will generate following JavaScript code −

//Generated by typescript 1.8.10
var display = function (x) {
   console.log("The function got " + x);
};
display(12);
Its output is as follows −

The function got 12

*/