

/* 

Optional braces for a single statement, Empty parentheses for no parameter
The following example shows these two Syntactic variations.

*/

var disp =()=> { 
    console.log("Function invoked"); 
 } 
 disp();

/* 
On compiling, it will generate following JavaScript code −

//Generated by typescript 1.8.10
var disp = function () {
   console.log("Function invoked");
};
disp();
Its output is as follows −

Function invoked

*/