


/* 

Array Destructuring
Refers to breaking up the structure of an entity. TypeScript supports destructuring when used in the context of an array.

Example

*/

var arr:number[] = [12,13] 
var[x,y] = arr 
console.log(x) 
console.log(y)

/* 

On compiling, it will generate following JavaScript code.

//Generated by typescript 1.8.10
var arr = [12, 13];
var x = arr[0], y = arr[1];
console.log(x);
console.log(y);

Its output is as follows −

12 
13


*/