


/* 

TypeScript - Variables
Advertisements
 Previous Page Next Page  
A variable, by definition, is “a named space in the memory” that stores values. In other words, it acts as a container for values in a program. TypeScript variables must follow the JavaScript naming rules −

Variable names can contain alphabets and numeric digits.

They cannot contain spaces and special characters, except the underscore (_) and the dollar ($) sign.

Variable names cannot begin with a digit.

A variable must be declared before it is used. Use the var keyword to declare variables.

Variable Declaration in TypeScript
The type syntax for declaring a variable in TypeScript is to include a colon (:) after the variable name, followed by its type. Just as in JavaScript, we use the var keyword to declare a variable.

When you declare a variable, you have four options −

Declare its type and value in one statement.

Declare Type
Declare its type but no value. In this case, the variable will be set to undefined.

Undefined
Declare its value but no type. The variable type will be set to any.

Any
Declare neither value not type. In this case, the data type of the variable will be any and will be initialized to undefined.

Any and Undefined
The following table illustrates the valid syntax for variable declaration as discussed above −

S.No.	Variable Declaration Syntax & Description
1.	
var name:string = ”mary”

The variable stores a value of type string

2.	
var name:string;

The variable is a string variable. The variable’s value is set to undefined by default

3.	
var name = ”mary”

The variable’s type is inferred from the data type of the value. Here, the variable is of the type string

4.	
var name;

The variable’s data type is any. Its value is set to undefined by default.

Example: Variables in TypeScript
*/

var names:string = "John"; 
var score1:number = 50;
var score2:number = 42.50
var sum = score1 + score2 
console.log("name"+names) 
console.log("first score: "+score1) 
console.log("second score: "+score2) 
console.log("sum of the scores: "+sum)

/* 

On compiling, it will generate following JavaScript code.

//Generated by typescript 1.8.10
var name = "John";
var score1 = 50;
var score2 = 42.50;
var sum = score1 + score2;
console.log("name" + name);
console.log("first score: " + score1);
console.log("second score : " + score2);
console.log("sum of the scores: " + sum);
The output of the above program is given below −

name:John 
first score:50 
second score:42.50 
sum of the scores:92.50

*/

