


/* 

Array Object
An array can also be created using the Array object. The Array constructor can be passed.

A numeric value that represents the size of the array or

A list of comma separated values.

The following example shows how to create an array using this method.

Example


*/

var arr_names:number[] = new Array(4)  

for(var i = 0;i<arr_names.length;i++ ) { 
   arr_names[i] = i * 2 
   console.log(arr_names[i]) 
}

/* 

On compiling, it will generate following JavaScript code.

//Generated by typescript 1.8.10
var arr_names = new Array(4);

for (var i = 0; i < arr_names.length; i++) {
   arr_names[i] = i * 2;
   console.log(arr_names[i]);
}
Its output is as follows −

0 
2 
4 
6 

*/