


/* 

The static Keyword
The static keyword can be applied to the data members of a class. A static variable retains its values till the program finishes execution. Static members are referenced by the class name.

Example

*/

class StaticMem {  
    static num:number; 
    
    static disp():void { 
       console.log("The value of num is"+ StaticMem.num) 
    } 
 } 
 
 StaticMem.num = 12     // initialize the static variable 
 StaticMem.disp()      // invoke the static method

 /* 
 
 On compiling, it will generate following JavaScript code.

//Generated by typescript 1.8.10
var StaticMem = (function () {
   function StaticMem() {
   }
	
   StaticMem.disp = function () {
      console.log("The value of num is" + StaticMem.num);
   };
	
   return StaticMem;
}());

StaticMem.num = 12;     // initialize the static variable
StaticMem.disp();      // invoke the static method
The output of the above code is as follows −

The value of num is 12

 */