



/*

Destructuring a Tuple
Destructuring refers to breaking up the structure of an entity. TypeScript supports destructuring when used in the context of a tuple.

Example

*/

var a =[10,"hello"] 
var [b,c] = a 
console.log( b )    
console.log( c ) 

/* 

On compiling, it will generate following JavaScript code.

//Generated by typescript 1.8.10
var a = [10, "hello"];
var b = a[0], c = a[1];
console.log(b);
console.log(c);
Its output is as follows −

10 
hello 

*/